dev:
  container_name: node-dev-tools
  image: toubiweb/node-dev:lts
  command: tail -f /dev/null
  hostname: node-dev-tools
  volumes:
    - .:/app
    - $HOME/.ssh:/home/dev/.ssh
    - $HOME/.gitconfig:/home/dev/.gitconfig
    - $HOME/.npmrc:/home/dev/.npmrc
